=== api-evangelist/thanx/json-schema/consumer-api-reward-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Reward",
  "description": "Reward schema from Thanx Consumer API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/thanx/refs/heads/main/json-schema/consumer-api-reward-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "olo_uid": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "user_id": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "merchant_id": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "campaign_id": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "state": {
      "type": "string",
      "enum": [
        "available",
        "active",
        "used"
      ],
      "example": "available"
    },
    "earn": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        }
      }
    },
    "redeem": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "detail": {
          "type": "string"
        },
        "window": {
          "type": "string"
        },
        "venue": {
          "type": "string"
        }
      }
    },
    "coupon_code": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      }
    },
    "fine_print": {
      "type": "string",
      "example": "Free coffee for loyal customers."
    },
    "instructions": {
      "type": "string",
      "example": "Free coffee for loyal customers."
    },
    "available_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "activated_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "retire_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "used_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "uses_dynamic_coupon_codes": {
      "type": "boolean",
      "example": true
    }
  }
}

=== api-evangelist/thanx/examples/consumer-api-reward-example.json
{
  "id": "92b7b0dac4",
  "olo_uid": "92b7b0dac4",
  "user_id": "92b7b0dac4",
  "merchant_id": "92b7b0dac4",
  "campaign_id": "92b7b0dac4",
  "state": "available",
  "earn": {
    "type": "example"
  },
  "redeem": {
    "type": "example",
    "text": "example",
    "detail": "example",
    "window": "example",
    "venue": "example"
  },
  "coupon_code": {
    "code": "example",
    "type": "example",
    "display": "example"
  },
  "fine_print": "Free coffee for loyal customers.",
  "instructions": "Free coffee for loyal customers.",
  "available_at": "2025-06-01T18:02:05Z",
  "activated_at": "2025-06-01T18:02:05Z",
  "retire_at": "2025-06-01T18:02:05Z",
  "used_at": "2025-06-01T18:02:05Z",
  "uses_dynamic_coupon_codes": true
}
