=== api-evangelist/thanx/json-schema/partner-api-campaign-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Campaign",
  "description": "Campaign schema from Thanx Partner API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/thanx/refs/heads/main/json-schema/partner-api-campaign-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "92b7b0dac4"
    },
    "name": {
      "type": "string",
      "example": "Pizza Town Co"
    },
    "objective": {
      "type": "string",
      "example": "Free coffee for loyal customers."
    },
    "start_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "end_at": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "redeemable_from": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "redeemable_to": {
      "type": "string",
      "format": "date-time",
      "example": "2025-06-01T18:02:05Z"
    },
    "time_zone": {
      "type": "string",
      "example": "example"
    },
    "fine_print": {
      "type": "string",
      "example": "Free coffee for loyal customers."
    },
    "variants": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "reward_template_id": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
  }
}

=== api-evangelist/thanx/examples/partner-api-campaign-example.json
{
  "id": "92b7b0dac4",
  "name": "Pizza Town Co",
  "objective": "Free coffee for loyal customers.",
  "start_at": "2025-06-01T18:02:05Z",
  "end_at": "2025-06-01T18:02:05Z",
  "redeemable_from": "2025-06-01T18:02:05Z",
  "redeemable_to": "2025-06-01T18:02:05Z",
  "time_zone": "example",
  "fine_print": "Free coffee for loyal customers.",
  "variants": [
    {
      "id": "92b7b0dac4",
      "name": "Pizza Town Co",
      "reward_template_id": "92b7b0dac4"
    }
  ]
}
